### ISSUE TITLE
Clarification for OSX  /substitute_find_private_syms  /test-find-syms.c

### ISSUE THREAD

**Issue by johndpope** [comex/substitute#12]
I clone the app 
run 
./configure --enable-tests && make -j8

now I want to run the compiled code
/out/test-find-syms
Segmentation fault: 11

other tests are ok.

is this a known issue? 
I understand the substrate wouldn't work on OSX - is it the same case with this code? 
(I had to manually copy the /usr/lib/libsubstitute.0.dylib into place)

test-find-syms.c
#include <substitute.h>
#include <stdio.h>
#include <assert.h>
#include <dlfcn.h>

    int main() {
	const char *foundation = "/System/Library/Frameworks/Foundation.framework/Foundation";
	dlopen(foundation, RTLD_LAZY);
	struct substitute_image *im = substitute_open_image(foundation);
	assert(im);
	const char *names[] = { "_absolute_from_gregorian" };
	int (*f)(int);
	assert(!substitute_find_private_syms(im, names, (void **) &f, 1));
	assert(f);

	assert(f(12345) < 0);

	substitute_close_image(im);
   }

When I dump the foundation.framework symbols - it doesn't include _absolute_from_gregorian.
Is that what this code is supposed to be doing?  I had hoped to call a private symbol using this code.

nm -gj /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation 

UPDATE

fyi - code to compile single test

mkdir -p out
/usr/bin/xcrun --sdk macosx cc -g -I./lib -I./substrate -I./vendor -std=c89 -fvisibility=hidden -O3 -c -o out/test-find-syms.o -MMD -MF /substitute/out/test-find-syms.d ./test/test-find-syms.c
/usr/bin/xcrun --sdk macosx cc -g -I./lib -I./substrate -I./vendor -x c++ -std=c++98 -fvisibility=hidden -O3 -c -o out/test-find-syms-cpp.o -MMD -MF /substitute/out/test-find-syms-cpp.d ./test/test-find-syms.c
/usr/bin/xcrun --sdk macosx cc -o /substitute/out/test-find-syms-cpp /substitute/out/libsubstitute.dylib out/test-find-syms-cpp.o -dead_strip -O3
/usr/bin/xcrun --sdk macosx dsymutil /substitute/out/test-find-syms-cpp
/usr/bin/xcrun --sdk macosx cc -o /substitute/out/test-find-syms /substitute/out/libsubstitute.dylib out/test-find-syms.o -dead_strip -O3
/usr/bin/xcrun --sdk macosx dsymutil /substitute/out/test-find-syms

Is it possible to call mangled c++ symbol names?

**Comment by comex** [comment]
Looks like a bug in my code which was exposed by OS X 10.11 no longer including a copy of private symbols in the shared cache.  (I guess because they're already in the original files, unlike on iOS?)  I just pushed a fix.

And yes, the purpose of the code is to call private symbols; if you remove -g from your nm command you'll see _absolute_from_gregorian.

It's possible to call mangled names, but you'll have to do the mangling yourself and get the calling convention right (for non-static methods, hidden this argument at the beginning).

Let me know if you run into any more problems.
