### ISSUE TITLE
Are you going to allow hooking into root apps?

### ISSUE THREAD

**Issue by rweichler** [comex/substitute#4]
Sorry for making another issue that's a question (well I guess this is more a feature request but still)

From what I've seen for substrate the only reason why it doesn't hook root apps is because of security concerns, but I don't really buy that reason... you can just hook into SpringBoard, add a .deb to the Cydia autoinstall directory (and have Cydia install something to rc.d as root) and you'd get the same effect.

Thoughts?

**Comment by comex** [comment]
Cydia runs as mobile now, doesn't it?  What other root apps exist?

**Comment by rweichler** [comment]
It uses setuid, so hooking it is still disable. iFile also runs as root.

**Comment by arcticsn0w** [comment]
iFile, Filza (although Filza runs as mobile with the beta)

**Comment by comex** [comment]
Oh.  I need to ask about this.  If I remember correctly, I was once told that the purpose of setuid Cydia was to act as a safety mechanism, ensuring the user had a way to uninstall bad tweaks.  But I'm not sure how that works:

- If the user knows the volume-up thingy, then they are safe no matter what.  Otherwise...
- If SpringBoard malfunctions but does not crash, the user will be unable to navigate into Cydia anyway.
- If SpringBoard crashes, then it will be reloaded in safe mode:
  - If Cydia is not affected by the crash, then preventing it from being hooked doesn't matter.
  - If other daemons *are* affected by the crash, then the system may not function well enough to let them actually use the app
  - Otherwise (Cydia is, other daemons aren't), keeping Cydia unhooked will save the user.

That's a relatively large list of assumptions for it to be useful, though perhaps they are common satisfied in practice.  But if that's the logic, why not just disable hooking for all apps when safe mode has been activated?  I could apply this to backboardd (since it's respringing anyway) and maybe a grab bag of other daemons that can be restarted without bothering the user too much, to maximize the chance the resulting system is usable.  Or perhaps have some automatic method to reboot into full safe mode, but then you have a fair possibility of false positives, and what if it doesn't crash...

However, it's not like saurik wouldn't have thought of that.  I clearly remember being told it was a safety feature, so I'll have to screw up my courage and ask him how this is supposed to work.

**Comment by rweichler** [comment]
> why not just disable hooking for all apps when safe mode has been activated?
```
17:55 < saurik> rweichler: "safe mode" is a concept that is only applicable to SpringBoard. part of the issue is dealing with what the UI would be for background daemons ending up in safe mode. it isn't like the entire system goes into a "safe mode", so there's no concept of entering or exiting safe mode. it would require like, some kind of GUI manager that told you what processes were loaded and whether they were injected...
17:55 < saurik> the volume-up-to-disable feature is much better for these background daemons
18:28 < rweichler> oh and yea i understand that issue with not knowing which daemons are safe-moded
18:28 < rweichler> but i think that it would make more sense if SpringBoard was safe-moded, then everything else would be too
18:29 < rweichler> cuz it says 'your device is in safe mode' afaik
18:29 < rweichler> actually... that would cause a lot of issues i feel like...
18:30 < rweichler> actually yeah.
18:31 < rweichler> if it goes into safemode, it kills all of the hooked daemons that are part of watchdog, and doesnt hook them
18:31 < rweichler> and then when you ask it to restart, then it does it again
18:32 < rweichler> what do you think?
21:42 < saurik> rweichler: that seems really overkill for a mere crash. a lot of developers have been on the other side, arguing that going into safe mode when crashes happen at all without the user requesting it in some way is draconian and intrusive, and users complain as well. the reality is that virtually all crash issues are isolated to one process
21:42 < saurik> and that process also happens to almost always be springboard. it sounds like maybe the real issue is the documentation in that dialog
21:42 < saurik> maybe it should say something like "SpringBoard is now in safe mode"
```

**Comment by rweichler** [comment]
This is just my personal opinion, but I think the underlying reason why substrate won't hook root applications is because of Cydia, since it would promote piracy. Julio Verne made a tweak called Cydia Enable, which allows you to choose which .dylibs you want to be able to hook as root via an app (and some cyinject magic I'm guessing).

https://twitter.com/iJulioVerne/status/544605827509014528

it ended up being rejected by ModMyi (https://twitter.com/iJulioVerne/status/546728442512019456), probably because he also made a tweak called CyDown which uses Cydia Enable to hook into Cydia and basically get free tweaks

**Comment by comex** [comment]
I appreciate the effort, but telephone isn't the best approach for this.  I'll ask him myself when I have time to work on this (maybe tomorrow).

**Comment by rweichler** [comment]
Oh, yeah that was a log from a while back, I didn't ask him just now haha.

**Comment by kirb** [comment]
My two cents:


The reason why Substrate doesn't directly load tweaks in a root process, as far as I know, is because it was said many assume they are running as mobile (so a file may be created in the wrong home dir, or with bad permissions, etc). If Cydia already loads a selected number of tweaks, I don't think there is a real problem of "a bad tweak could make it impossible to open Cydia to uninstall". (I mean, that's what safe mode/no subst{rate,itute} mode are for.) Plus, the concept of Cydia Enable also proves the same. 




Tweaks should opt in to being loaded into root apps with a filter plits key. If I recall correctly Activator has `SupportsRoot=YES` despite Substrate not reading such a key. Might as well use that. Majority of tweaks should probably be fine as is without needing fixes, but better to be opt in for the ones that aren't.



–
Adam D
HASHBANG Productions
http://hbang.ws

**Comment by kirb** [comment]
Also, I was fairly certain Safe Mode hooks backboardd to set an environment variable while spawning apps so Substrate is disabled in them?



–
Adam D
HASHBANG Productions
http://hbang.ws

**Comment by rweichler** [comment]
gonna clopse this since this isn't really relevant anymore
